"""add_account

Revision ID: 035c5bbcf4d6
Revises: 75533741767d
Create Date: 2025-01-08 14:46:15.021813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035c5bbcf4d6'
down_revision: Union[str, None] = '75533741767d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheques', sa.Column('account', sa.String(), nullable=False))
    op.alter_column('cheques', 'seller',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cheques', 'seller',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cheques', 'account')
    # ### end Alembic commands ###
