"""Add purchase_date

Revision ID: 03bd0001c647
Revises: af9586858005
Create Date: 2025-01-07 20:33:35.098059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bd0001c647'
down_revision: Union[str, None] = 'af9586858005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheques', sa.Column('purchase_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheques', 'purchase_date')
    # ### end Alembic commands ###
