"""Add Pattern model

Revision ID: 8c94410aa9fd
Revises: aef528460f46
Create Date: 2025-01-13 10:24:44.936609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c94410aa9fd'
down_revision: Union[str, None] = 'aef528460f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_in', sa.String(), nullable=False),
    sa.Column('field_in', sa.String(), nullable=False),
    sa.Column('include', sa.String(), nullable=False),
    sa.Column('model_out', sa.String(), nullable=False),
    sa.Column('field_out', sa.String(), nullable=False),
    sa.Column('value_out', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('cheque_details', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cheque_details', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('patterns')
    # ### end Alembic commands ###
