"""add category field

Revision ID: aef528460f46
Revises: 720d9065473f
Create Date: 2025-01-10 18:01:21.117777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef528460f46'
down_revision: Union[str, None] = '720d9065473f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheque_details', sa.Column('category', sa.String(length=20), nullable=False, default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cheque_details', 'category')
    # ### end Alembic commands ###
