name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory /home/github/bills_service

      - name: Deploy to Server
        run: |
          cd /home/github/bills_service
          pwd
          git pull origin master
          docker compose down
          docker compose --env-file .env up -d --build
          docker compose exec bills poetry run alembic upgrade head
          EOF