name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Prepare .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy to Server
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'ENDSSH'
          cd ~/bills_service
          git pull origin main
          docker compose down
          docker-compose --env-file .env up -d --build
          docker compose exec bills poetry run alembic upgrade head
          ENDSSH