name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          pwd
          ls -la .env
          git pull origin main
          docker compose down
          docker compose --env-file .env up -d --build
          docker compose exec bills poetry run alembic upgrade head
          EOF